name: CI/CD

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Check
      run: make check

  lint: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Lint
      run: make lint

  format: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Format
      run: make format

  build:
    runs-on: ubuntu-latest
    needs: [ check, lint, format ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: make build

  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: make test
